# SPDX-License-Identifier: Apache-2.0

CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=8192

CONFIG_WAMR=y
CONFIG_WAMR_INTERP=y
CONFIG_WAMR_FAST_INTERP=n
CONFIG_WAMR_AOT=n
CONFIG_WAMR_LIBC_BUILTIN=n
CONFIG_WAMR_LIBC_WASI=n
CONFIG_WAMR_GLOBAL_HEAP_POOL=y
CONFIG_WAMR_GLOBAL_HEAP_SIZE=131072

CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_PSA_CRYPTO_C=y
CONFIG_MBEDTLS_PSA_STATIC_KEY_SLOTS=y
CONFIG_MBEDTLS_PSA_KEY_SLOT_COUNT=2
CONFIG_PSA_WANT_KEY_TYPE_ECC_PUBLIC_KEY=y
CONFIG_PSA_WANT_ECC_SECP_R1_256=y
CONFIG_PSA_WANT_ALG_ECDSA=y
CONFIG_PSA_WANT_ALG_SHA_256=y

# Simulator-only: the RT1170 CAAM entropy peripheral is not modelled by Renode.
CONFIG_TEST_RANDOM_GENERATOR=y
