# SPDX-License-Identifier: Apache-2.0

CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=8192

CONFIG_WAMR=y
CONFIG_WAMR_INTERP=y
CONFIG_WAMR_FAST_INTERP=n
CONFIG_WAMR_AOT=n
CONFIG_WAMR_LIBC_BUILTIN=n
CONFIG_WAMR_LIBC_WASI=n
CONFIG_WAMR_GLOBAL_HEAP_POOL=y
CONFIG_WAMR_GLOBAL_HEAP_SIZE=131072
